[package]
name = "ssg"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
arneos = { path = "../arneos" }
blake3 = "1.5.4"
chrono = { version = "0.4.38", default-features = false, features = [
    "std",
    "clock",
    "serde",
] }
grass = { version = "0.13", default-features = false }
maud = { version = "0.26" }
quick-xml = { version = "0.37", features = ["serialize"] }
rss = "2"
serde = { version = "1", features = ["derive"] }
tempdir = "0.3"
ureq = "2.10"
url = { version = "2.5", features = ["serde"] }
zip = "2.2"
