[package]
name = "arne-me"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
chrono = { version = "0.4.31", default-features = false, features = ["std", "clock", "serde"] }
clap = { version = "4", features = ["derive"] }
comrak = { version = "0.19.0", default-features = false, features = ["emojis", "syntect" ] }
grass = { version = "0.13", default-features = false }
gray_matter = "0.2"
maud = { version = "0.25", features = ["axum"] }
quick-xml = { version ="0.31", features = ["serialize"] }
rss = "2"
serde = { version = "1", features = ["derive"] }
url = { version = "2.4", features = ["serde"] }
