[package]
name = "arne-me"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.31", default-features = false, features = ["std", "clock"] }
maud = { version = "0.25", features = ["axum"] }
url = { version = "2.4", features = ["serde"] }
