title = "Arne Bahlo"
description = "The personal website of Arne Bahlo."
base_url = "https://arne.me"
compile_sass = true
build_search_index = true
# minify_html = true # broken
generate_feed = true

[markdown]
highlight_code = true
smart_punctuation = false

[extra]
navbar_items = [
  # { path = "/", name = "Home" }, # static logo
  { path = "/projects/", name = "Projects" },
  { path = "/work/", name = "Work" },
  { path = "/blog/", name = "Blog" },
]
author = "Arne Bahlo"
git_sha = "219f7c8"
primary_color = "rgb(259, 178, 143)"
plausible_domain = "arne.me"
