title = "Arne Bahlo"
description = "The personal website of Arne Bahlo."
base_url = "https://arne.me"
compile_sass = true
build_search_index = true
# minify_html = true # broken

[markdown]
highlight_code = true
smart_punctuation = false

[extra]
navbar_items = [
  # { path = "/", name = "Home" }, # static logo
  { path = "/projects/", name = "Projects" },
  { path = "/work/", name = "Work" },
  { path = "/blog/", name = "Blog" },
]