base_url = "https://arne.me"
compile_sass = true
build_search_index = true
title = "Arne Bahlo"

[markdown]
highlight_code = true

[extra]
navbar_items = [
  # { path = "/", name = "Home" }, # static logo
  { path = "/projects/", name = "Projects" },
  { path = "/experience/", name = "Experience" },
]
