title = "Arne Bahlo"
description = "The personal website of Arne Bahlo."
base_url = "https://arne.me"
compile_sass = true
build_search_index = true
generate_feed = true

[markdown]
smart_punctuation = true
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["extra_highlight_themes"]
# highlight_themes_css = [
#   { theme = "base16-unikitty-dark", filename = "syntax-theme-dark.css" },
#   { theme = "base16-unikitty-light", filename = "syntax-theme-light.css" },
# ]

[extra]
navbar_items = [
  # { path = "/", name = "Home" }, # static logo
  { path = "/projects/", name = "Projects" },
  { path = "/work/", name = "Work" },
  { path = "/blog/", name = "Blog" },
]
author = "Arne Bahlo"
git_sha = "d03d449"
primary_color = "#e29799"
primary_color_rgb = [ 225, 151, 153 ]
plausible_domain = "arne.me"
authn_email = "hey@arne.me"
webmention_io_username = "arne.me"
