backend:
  name: github
  repo: bahlo/arne.me
  branch: main
media_folder: "static/img"
public_folder: "/static/img"

# Run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Blogpost"
    name: "blogposts"
    folder: "posts"
    create: true
    editor:
      preview: false
    fields:
      - widget: "string"
        label: "Title"
        name: "title"
      - widget: "string"
        label: "Description"
        name: "description"
      - widget: "datetime"
        label: "Publish Date"
        name: "date"
      - widget: "boolean"
        label: "Draft"
        name: "draft"
      - label: "Body"
        name: "body"
        widget: "markdown"
  - label: "Link"
    name: "link"
    folder: "links"
    create: true
    editor:
      preview: false
    fields:
      - widget: "string"
        label: "Title"
        name: "title"
      - widget: "string"
        label: "URL"
        name: "url"
      - widget: "datetime"
        label: "Publish Date"
        name: "date"
      - widget: "boolean"
        label: "Draft"
        name: "draft"
      - label: "Body"
        name: "body"
        widget: "markdown"
  - label: "Book"
    name: "books"
    folder: "books"
    create: true
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Author"
        name: "author"
        widget: "string"
      - label: "ISBN"
        name: "isbn"
        widget: "string"
      - label: "Cover"
        name: "cover"
        widget: "image"
        allow_multiple: false
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - widget: "boolean"
        label: "Draft"
        name: "draft"
      - label: "Body"
        name: "body"
        widget: "markdown"
  - label: "Photo"
    name: "photos"
    folder: "photos"
    create: true
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Photo"
        name: "photo"
        widget: "image"
        allow_multiple: false
      - label: "Alt text"
        name: "altText"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - widget: "boolean"
        label: "Draft"
        name: "draft"
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Metadata"
        name: "metadata"
        file: "_data/metadata.yaml"
        fields:
          - label: Title
            name: title
            widget: string
          - label: URL
            name: url
            widget: string
          - label: Description
            name: description
            widget: string
          - label: Feed
            name: feed
            widget: object
            fields:
              - label: Filename
                name: filename
                widget: string
              - label: Path
                name: path
                widget: string
              - label: ID
                name: id
                widget: string
          - label: Author
            name: author
            widget: object
            fields:
              - label: Name
                name: name
                widget: string
              - label: Email
                name: email
                widget: string
