backend:
  name: github
  repo: bahlo/arne.me
  branch: main
media_folder: "static/img"
public_folder: "/static/img"

# Run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Blog"
    name: "blog"
    folder: "posts"
    create: true
    editor:
      preview: false
    fields:
      - widget: "string"
        label: "Title"
        name: "title"
      - widget: "string"
        label: "Description"
        name: "description"
      - widget: "datetime"
        label: "Publish Date"
        name: "date"
      - label: "Body"
        name: "body"
        widget: "markdown"
