name: Automation

on:
  push:
    branches:
      - main
    paths:
      - 'content/**.md'

jobs:
  automate:
    name: Automate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # All history
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-cli-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('crates/**') }}
          restore-keys: cargo-cli-
      - run: cargo run automate --before-sha ${{ github.event.before }}
        env:
          MASTODON_URL: https://spezi.social
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
