name: CI

on:
  schedule:
    - cron: "0 0 1 1 *"
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-all-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('crates/**') }}
          restore-keys: cargo-all-
      - run: cargo check
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-all-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('crates/**') }}
          restore-keys: cargo-all-
      - run: cargo test
  build-deploy:
    name: Build & deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      # Necessary to commit new OG images
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-ssg-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('crates/**') }}
          restore-keys: cargo-ssg-
      - run: cargo run -p ssg -- --generate-missing-og-images
        env:
          FONT_ZIP_URL: "${{ secrets.FONT_ZIP_URL }}"
      - uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5.1.0
        id: commit-og-images
        with:
          commit_message: "Add missing OG images"
          file_pattern: "**/og-image.png"
          disable_globbing: true
      - uses: nwtgck/actions-netlify@4cbaf4c08f1a7bfa537d6113472ef4424e4eb654 # v3.0.0
        with:
          publish-dir: "./dist"
          production-deploy: true
          enable-github-deployment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - uses: axiomhq/annotation-action@403f688c009395bd13282b995ebd0bebe6df9443 # v0.1.0
        with:
          axiomToken: ${{ secrets.AXIOM_TOKEN}}
          datasets: netlify
          type: deployment
          title: Production deployment
          description: ${{ github.event.head_commit.message }}
