name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo run -p ssg
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: dist
          commit-message: "Deploying to dist from ${{ github.sha }}"
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          ssh-key: ${{ secrets.DIST_REPO_PK }}
          branch: main
          repository-name: "bahlo/arne-me-dist"
          commit-message: "Deploying to arne-me-dist from https://github.com/bahlo/arne.me/commit/${{ github.sha }}"
