name: Syndicate

on:
  push:
    branches:
      - main
    paths:
      - 'content/**.md'

jobs:
  syndicate:
    name: Syndicate
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: |
          git diff --stat ${{ github.event.before }}
