name: Syndicate

on:
  push:
    branches:
      - main
    paths:
      - 'content/**.md'

jobs:
  syndicate:
    name: Syndicate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo run syndicate ${{ github.event.before }}
