name: Syndicate

on:
  push:
    branches:
      - main
    paths:
      - 'content/**.md'

jobs:
  syndicate:
    name: Syndicate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git diff --stat ${{ github.event.before }}
