name: Syndicate

on:
  push:
    branches:
      - main
    paths:
      - 'content/**.md'

jobs:
  syndicate:
    name: Syndicate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # All history
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo run syndicate --before-sha ${{ github.event.before }}
        env:
          AXIOM_URL: https://spezi.social
          AXIOM_TOKEN: ${{ secrets.AXIOM_TOKEN}}
